import { TarotCard } from "@/types/tarotCard.type";

export const tarotCards: TarotCard[] = [
  // Major Arcana
  {
    name: "The Fool",
    type: "Major Arcana",
    image: "/images/theFool.png",
    index: 0,
  },
  {
    name: "The Magician",
    type: "Major Arcana",
    image: "/images/theMagician.png",
    index: 1,
  },
  {
    name: "The High Priestess",
    type: "Major Arcana",
    image: "/images/The High Priestess.jpg",
    index: 2,
  },
  {
    name: "The Empress",
    type: "Major Arcana",
    image: "/images/The Empress.jpg",
    index: 3,
  },
  {
    name: "The Emperor",
    type: "Major Arcana",
    image: "/images/The Emperor.jpg",
    index: 4,
  },
  {
    name: "The Hierophant",
    type: "Major Arcana",
    image: "/images/The Hierophant.jpg",
    index: 5,
  },
  {
    name: "The Lovers",
    type: "Major Arcana",
    image: "/images/The Lovers.jpg",
    index: 6,
  },
  {
    name: "The Chariot",
    type: "Major Arcana",
    image: "/images/The Chariot.jpg",
    index: 7,
  },
  {
    name: "Strength",
    type: "Major Arcana",
    image: "/images/Strength.jpg",
    index: 8,
  },
  {
    name: "The Hermit",
    type: "Major Arcana",
    image: "/images/The Hermit.jpg",
    index: 9,
  },
  {
    name: "Wheel of Fortune",
    type: "Major Arcana",
    image: "/images/Wheel of Fortune.jpg",
    index: 10,
  },
  {
    name: "Justice",
    type: "Major Arcana",
    image: "/images/Justice.jpg",
    index: 11,
  },
  {
    name: "The Hanged Man",
    type: "Major Arcana",
    image: "/images/The Hanged Man.jpg",
    index: 12,
  },
  {
    name: "Death",
    type: "Major Arcana",
    image: "/images/Death.jpg",
    index: 13,
  },
  {
    name: "Temperance",
    type: "Major Arcana",
    image: "/images/Temperance.jpg",
    index: 14,
  },
  {
    name: "The Devil",
    type: "Major Arcana",
    image: "/images/The Devil.jpg",
    index: 15,
  },
  {
    name: "The Tower",
    type: "Major Arcana",
    image: "/images/The Tower.jpg",
    index: 16,
  },
  {
    name: "The Star",
    type: "Major Arcana",
    image: "/images/The Star.jpg",
    index: 17,
  },
  {
    name: "The Moon",
    type: "Major Arcana",
    image: "/images/The Moon.jpg",
    index: 18,
  },
  {
    name: "The Sun",
    type: "Major Arcana",
    image: "/images/The Sun.jpg",
    index: 19,
  },
  {
    name: "Judgement",
    type: "Major Arcana",
    image: "/images/Judgement.jpg",
    index: 20,
  },
  {
    name: "The World",
    type: "Major Arcana",
    image: "/images/The World.jpg",
    index: 21,
  },
  // Minor Arcana - Wands
  {
    name: "Ace of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 1,
    image: "/images/Ace of Wands.jpg",
    index: 22,
  },
  {
    name: "Two of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 2,
    image: "/images/Two of Wands.jpg",
    index: 23,
  },
  {
    name: "Three of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 3,
    image: "/images/Three of Wands.jpg",
    index: 24,
  },
  {
    name: "Four of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 4,
    image: "/images/Four of Wands.jpg",
    index: 25,
  },
  {
    name: "Five of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 5,
    image: "/images/Five of Wands.jpg",
    index: 26,
  },
  {
    name: "Six of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 6,
    image: "/images/Six of Wands.jpg",
    index: 27,
  },
  {
    name: "Seven of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 7,
    image: "/images/Seven of Wands.jpg",
    index: 28,
  },
  {
    name: "Eight of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 8,
    image: "/images/Eight of Wands.jpg",
    index: 29,
  },
  {
    name: "Nine of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 9,
    image: "/images/Nine of Wands.jpg",
    index: 30,
  },
  {
    name: "Ten of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 10,
    image: "/images/Ten of Wands.jpg",
    index: 31,
  },
  {
    name: "Page of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    image: "/images/Page of Wands.jpg",
    index: 32,
  },
  {
    name: "Knight of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    image: "/images/Knight of Wands.jpg",
    index: 33,
  },
  {
    name: "Queen of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    image: "/images/Queen of Wands.jpg",
    index: 34,
  },
  {
    name: "King of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    image: "/images/King of Wands.jpg",
    index: 35,
  },
  // Minor Arcana - Cups
  {
    name: "Ace of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 1,
    image: "/images/Ace of Cups.jpg",
    index: 36,
  },
  {
    name: "Two of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 2,
    image: "/images/Two of Cups.jpg",
    index: 37,
  },
  {
    name: "Three of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 3,
    image: "/images/Three of Cups.jpg",
    index: 38,
  },
  {
    name: "Four of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 4,
    image: "/images/Four of Cups.jpg",
    index: 39,
  },
  {
    name: "Five of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 5,
    image: "/images/Five of Cups.jpg",
    index: 40,
  },
  {
    name: "Six of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 6,
    image: "/images/Six of Cups.jpg",
    index: 41,
  },
  {
    name: "Seven of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 7,
    image: "/images/Seven of Cups.jpg",
    index: 42,
  },
  {
    name: "Eight of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 8,
    image: "/images/Eight of Cups.jpg",
    index: 43,
  },
  {
    name: "Nine of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 9,
    image: "/images/Nine of Cups.jpg",
    index: 44,
  },
  {
    name: "Ten of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 10,
    image: "/images/Ten of Cups.jpg",
    index: 45,
  },
  {
    name: "Page of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    image: "/images/Page of Cups.jpg",
    index: 46,
  },
  {
    name: "Knight of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    image: "/images/Knight of Cups.jpg",
    index: 47,
  },
  {
    name: "Queen of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    image: "/images/Queen of Cups.jpg",
    index: 48,
  },
  {
    name: "King of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    image: "/images/King of Cups.jpg",
    index: 49,
  },
  // Minor Arcana - Swords
  {
    name: "Ace of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 1,
    image: "/images/Ace of Swords.jpg",
    index: 50,
  },
  {
    name: "Two of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 2,
    image: "/images/Two of Swords.jpg",
    index: 51,
  },
  {
    name: "Three of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 3,
    image: "/images/Three of Swords.jpg",
    index: 52,
  },
  {
    name: "Four of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 4,
    image: "/images/Four of Swords.jpg",
    index: 53,
  },
  {
    name: "Five of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 5,
    image: "/images/Five of Swords.jpg",
    index: 54,
  },
  {
    name: "Six of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 6,
    image: "/images/Six of Swords.jpg",
    index: 55,
  },
  {
    name: "Seven of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 7,
    image: "/images/Seven of Swords.jpg",
    index: 56,
  },
  {
    name: "Eight of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 8,
    image: "/images/Eight of Swords.jpg",
    index: 57,
  },
  {
    name: "Nine of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 9,
    image: "/images/Nine of Swords.jpg",
    index: 58,
  },
  {
    name: "Ten of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 10,
    image: "/images/Ten of Swords.jpg",
    index: 59,
  },
  {
    name: "Page of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    image: "/images/Page of Swords.jpg",
    index: 60,
  },
  {
    name: "Knight of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    image: "/images/Knight of Swords.jpg",
    index: 61,
  },
  {
    name: "Queen of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    image: "/images/Queen of Swords.jpg",
    index: 62,
  },
  {
    name: "King of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    image: "/images/King of Swords.jpg",
    index: 63,
  },
  // Minor Arcana - Pentacles
  {
    name: "Ace of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 1,
    image: "/images/Ace of Pentacles.jpg",
    index: 64,
  },
  {
    name: "Two of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 2,
    image: "/images/Two of Pentacles.jpg",
    index: 65,
  },
  {
    name: "Three of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 3,
    image: "/images/Three of Pentacles.jpg",
    index: 66,
  },
  {
    name: "Four of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 4,
    image: "/images/Four of Pentacles.jpg",
    index: 67,
  },
  {
    name: "Five of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 5,
    image: "/images/Five of Pentacles.jpg",
    index: 68,
  },
  {
    name: "Six of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 6,
    image: "/images/Six of Pentacles.jpg",
    index: 69,
  },
  {
    name: "Seven of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 7,
    image: "/images/Seven of Pentacles.jpg",
    index: 70,
  },
  {
    name: "Eight of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 8,
    image: "/images/Eight of Pentacles.jpg",
    index: 71,
  },
  {
    name: "Nine of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 9,
    image: "/images/Nine of Pentacles.jpg",
    index: 72,
  },
  {
    name: "Ten of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 10,
    image: "/images/Ten of Pentacles.jpg",
    index: 73,
  },
  {
    name: "Page of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    image: "/images/Page of Pentacles.jpg",
    index: 74,
  },
  {
    name: "Knight of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    image: "/images/Knight of Pentacles.jpg",
    index: 75,
  },
  {
    name: "Queen of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    image: "/images/Queen of Pentacles.jpg",
    index: 76,
  },
  {
    name: "King of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    image: "/images/King of Pentacles.jpg",
    index: 77,
  },
];

export const tarotCardMap = new Map(
  tarotCards.map((card, index) => [card.name, index])
);
