import { TarotCard } from "@/types/tarotCard.type";

export const tarotCards: TarotCard[] = [
  // Major Arcana
  {
    name: "The Fool",
    type: "Major Arcana",
    image: "/images/theFool.png",
    index: 0,
    keywords: ["beginnings", "innocence", "spontaneity", "free spirit"],
  },
  {
    name: "The Magician",
    type: "Major Arcana",
    image: "/images/theMagician.png",
    index: 1,
    keywords: ["manifestation", "resourcefulness", "power", "inspired action"],
  },
  {
    name: "The High Priestess",
    type: "Major Arcana",
    image: "/images/theHighPriestess.png",
    index: 2,
    keywords: [
      "intuition",
      "sacred knowledge",
      "divine feminine",
      "subconscious mind",
    ],
  },
  {
    name: "The Empress",
    type: "Major Arcana",
    image: "/images/theEmpress.png",
    index: 3,
    keywords: ["femininity", "beauty", "nature", "nurturing", "abundance"],
  },
  {
    name: "The Emperor",
    type: "Major Arcana",
    image: "/images/theEmperor.png",
    index: 4,
    keywords: ["authority", "establishment", "structure", "control"],
  },
  {
    name: "The Hierophant",
    type: "Major Arcana",
    image: "/images/theHierophant.png",
    index: 5,
    keywords: [
      "spiritual wisdom",
      "religious beliefs",
      "conformity",
      "tradition",
      "institutions",
    ],
  },
  {
    name: "The Lovers",
    type: "Major Arcana",
    image: "/images/theLovers.png",
    index: 6,
    keywords: [
      "love",
      "harmony",
      "relationships",
      "values alignment",
      "choices",
    ],
  },
  {
    name: "The Chariot",
    type: "Major Arcana",
    image: "/images/theChariot.png",
    index: 7,
    keywords: ["control", "willpower", "success", "action", "determination"],
  },
  {
    name: "Strength",
    type: "Major Arcana",
    image: "/images/theStrength.png",
    index: 8,
    keywords: ["strength", "courage", "persuasion", "influence", "compassion"],
  },
  {
    name: "The Hermit",
    type: "Major Arcana",
    image: "/images/theHermit.png",
    index: 9,
    keywords: [
      "soul-searching",
      "introspection",
      "being alone",
      "inner guidance",
    ],
  },
  {
    name: "Wheel of Fortune",
    type: "Major Arcana",
    image: "/images/wheelOfFortune.png",
    index: 10,
    keywords: [
      "good luck",
      "karma",
      "life cycles",
      "destiny",
      "a turning point",
    ],
  },
  {
    name: "Justice",
    type: "Major Arcana",
    image: "/images/justice.png",
    index: 11,
    keywords: ["justice", "fairness", "truth", "cause and effect", "law"],
  },
  {
    name: "The Hanged Man",
    type: "Major Arcana",
    image: "/images/theHangedMan.png",
    index: 12,
    keywords: ["pause", "surrender", "letting go", "new perspectives"],
  },
  {
    name: "Death",
    type: "Major Arcana",
    image: "/images/death.png",
    index: 13,
    keywords: ["endings", "change", "transformation", "transition"],
  },
  {
    name: "Temperance",
    type: "Major Arcana",
    image: "/images/temperance.png",
    index: 14,
    keywords: ["balance", "moderation", "patience", "purpose"],
  },
  {
    name: "The Devil",
    type: "Major Arcana",
    image: "/images/theDevil.png",
    index: 15,
    keywords: [
      "shadow self",
      "attachment",
      "addiction",
      "restriction",
      "sexuality",
    ],
  },
  {
    name: "The Tower",
    type: "Major Arcana",
    image: "/images/theTower.png",
    index: 16,
    keywords: ["sudden change", "upheaval", "chaos", "revelation", "awakening"],
  },
  {
    name: "The Star",
    type: "Major Arcana",
    image: "/images/theStar.png",
    index: 17,
    keywords: ["hope", "faith", "purpose", "renewal", "spirituality"],
  },
  {
    name: "The Moon",
    type: "Major Arcana",
    image: "/images/theMoon.png",
    index: 18,
    keywords: ["illusion", "fear", "anxiety", "subconscious", "intuition"],
  },
  {
    name: "The Sun",
    type: "Major Arcana",
    image: "/images/theSun.png",
    index: 19,
    keywords: ["positivity", "fun", "warmth", "success", "vitality"],
  },
  {
    name: "Judgement",
    type: "Major Arcana",
    image: "/images/judgement.png",
    index: 20,
    keywords: ["judgement", "rebirth", "inner calling", "absolution"],
  },
  {
    name: "The World",
    type: "Major Arcana",
    image: "/images/theWorld.png",
    index: 21,
    keywords: ["completion", "integration", "accomplishment", "travel"],
  },
  // Minor Arcana - Wands
  {
    name: "Ace of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 1,
    image: "/images/aceOfWands.png",
    index: 22,
    keywords: ["inspiration", "new opportunities", "growth", "potential"],
  },
  {
    name: "Two of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 2,
    image: "/images/twoOfWands.png",
    index: 23,
    keywords: [
      "planning",
      "making decisions",
      "leaving comfort zone",
      "discovery",
    ],
  },
  {
    name: "Three of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 3,
    image: "/images/threeOfWands.png",
    index: 24,
    keywords: ["progress", "expansion", "foresight", "overseas opportunities"],
  },
  {
    name: "Four of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 4,
    image: "/images/fourOfWands.png",
    index: 25,
    keywords: ["celebration", "harmony", "homecoming", "community"],
  },
  {
    name: "Five of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 5,
    image: "/images/fiveOfWands.png",
    index: 26,
    keywords: [
      "conflict",
      "disagreement",
      "competition",
      "tension",
      "diversity",
    ],
  },
  {
    name: "Six of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 6,
    image: "/images/sixOfWands.png",
    index: 27,
    keywords: ["success", "public recognition", "progress", "self-confidence"],
  },
  {
    name: "Seven of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 7,
    image: "/images/sevenOfWands.png",
    index: 28,
    keywords: ["challenge", "competition", "protection", "perseverance"],
  },
  {
    name: "Eight of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 8,
    image: "/images/eightOfWands.png",
    index: 29,
    keywords: ["movement", "fast paced change", "action", "alignment"],
  },
  {
    name: "Nine of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 9,
    image: "/images/nineOfWands.png",
    index: 30,
    keywords: [
      "resilience",
      "courage",
      "persistence",
      "test of faith",
      "boundaries",
    ],
  },
  {
    name: "Ten of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    number: 10,
    image: "/images/tenOfWands.png",
    index: 31,
    keywords: ["burden", "extra responsibility", "hard work", "completion"],
  },
  {
    name: "Page of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    image: "/images/pageOfWands.png",
    index: 32,
    keywords: [
      "inspiration",
      "ideas",
      "discovery",
      "limitless potential",
      "free spirit",
    ],
  },
  {
    name: "Knight of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    image: "/images/knightOfWands.png",
    index: 33,
    keywords: [
      "energy",
      "passion",
      "inspired action",
      "adventure",
      "impulsiveness",
    ],
  },
  {
    name: "Queen of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    image: "/images/queenOfWands.png",
    index: 34,
    keywords: [
      "courage",
      "confidence",
      "independence",
      "social butterfly",
      "determination",
    ],
  },
  {
    name: "King of Wands",
    type: "Minor Arcana",
    suit: "Wands",
    image: "/images/kingOfWands.png",
    index: 35,
    keywords: ["natural-born leader", "vision", "entrepreneur", "honor"],
  },
  // Minor Arcana - Cups
  {
    name: "Ace of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 1,
    image: "/images/aceOfCups.png",
    index: 36,
    keywords: ["love", "new relationships", "compassion", "creativity"],
  },
  {
    name: "Two of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 2,
    image: "/images/twoOfCups.png",
    index: 37,
    keywords: ["unified love", "partnership", "mutual attraction"],
  },
  {
    name: "Three of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 3,
    image: "/images/threeOfCups.png",
    index: 38,
    keywords: ["celebration", "friendship", "creativity", "collaborations"],
  },
  {
    name: "Four of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 4,
    image: "/images/fourOfCups.png",
    index: 39,
    keywords: ["meditation", "contemplation", "apathy", "reevaluation"],
  },
  {
    name: "Five of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 5,
    image: "/images/fiveOfCups.png",
    index: 40,
    keywords: ["regret", "failure", "disappointment", "pessimism"],
  },
  {
    name: "Six of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 6,
    image: "/images/sixOfCups.png",
    index: 41,
    keywords: ["revisiting the past", "childhood memories", "innocence", "joy"],
  },
  {
    name: "Seven of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 7,
    image: "/images/sevenOfCups.png",
    index: 42,
    keywords: ["opportunities", "choices", "wishful thinking", "illusion"],
  },
  {
    name: "Eight of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 8,
    image: "/images/eightOfCups.png",
    index: 43,
    keywords: ["disappointment", "abandonment", "withdrawal", "escapism"],
  },
  {
    name: "Nine of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 9,
    image: "/images/nineOfCups.png",
    index: 44,
    keywords: ["contentment", "satisfaction", "gratitude", "wish come true"],
  },
  {
    name: "Ten of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    number: 10,
    image: "/images/tenOfCups.png",
    index: 45,
    keywords: ["divine love", "blissful relationships", "harmony", "alignment"],
  },
  {
    name: "Page of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    image: "/images/pageOfCups.png",
    index: 46,
    keywords: [
      "creative opportunities",
      "intuitive messages",
      "curiosity",
      "possibility",
    ],
  },
  {
    name: "Knight of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    image: "/images/knightOfCups.png",
    index: 47,
    keywords: ["romance", "charm", "imagination", "beauty"],
  },
  {
    name: "Queen of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    image: "/images/queenOfCups.png",
    index: 48,
    keywords: [
      "compassionate",
      "caring",
      "emotionally stable",
      "intuitive",
      "in flow",
    ],
  },
  {
    name: "King of Cups",
    type: "Minor Arcana",
    suit: "Cups",
    image: "/images/kingOfCups.png",
    index: 49,
    keywords: ["emotionally balanced", "compassion", "diplomacy"],
  },
  // Minor Arcana - Swords
  {
    name: "Ace of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 1,
    image: "/images/aceOfSwords.png",
    index: 50,
    keywords: ["breakthrough", "clarity", "sharp mind"],
  },
  {
    name: "Two of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 2,
    image: "/images/twoOfSwords.png",
    index: 51,
    keywords: [
      "difficult decisions",
      "weighing up options",
      "an impasse",
      "avoidance",
    ],
  },
  {
    name: "Three of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 3,
    image: "/images/threeOfSwords.png",
    index: 52,
    keywords: ["heartbreak", "emotional pain", "sorrow", "grief", "hurt"],
  },
  {
    name: "Four of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 4,
    image: "/images/fourOfSwords.png",
    index: 53,
    keywords: [
      "rest",
      "relaxation",
      "meditation",
      "contemplation",
      "recuperation",
    ],
  },
  {
    name: "Five of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 5,
    image: "/images/fiveOfSwords.png",
    index: 54,
    keywords: [
      "conflict",
      "disagreements",
      "competition",
      "defeat",
      "winning at all costs",
    ],
  },
  {
    name: "Six of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 6,
    image: "/images/sixOfSwords.png",
    index: 55,
    keywords: ["transition", "change", "rite of passage", "releasing baggage"],
  },
  {
    name: "Seven of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 7,
    image: "/images/sevenOfSwords.png",
    index: 56,
    keywords: [
      "betrayal",
      "deception",
      "getting away with something",
      "acting strategically",
    ],
  },
  {
    name: "Eight of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 8,
    image: "/images/eightOfSwords.png",
    index: 57,
    keywords: [
      "negative thoughts",
      "self-imposed restriction",
      "imprisonment",
      "victim mentality",
    ],
  },
  {
    name: "Nine of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 9,
    image: "/images/nineOfSwords.png",
    index: 58,
    keywords: ["anxiety", "worry", "fear", "depression", "nightmares"],
  },
  {
    name: "Ten of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    number: 10,
    image: "/images/tenOfSwords.png",
    index: 59,
    keywords: ["painful endings", "deep wounds", "betrayal", "loss", "crisis"],
  },
  {
    name: "Page of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    image: "/images/pageOfSwords.png",
    index: 60,
    keywords: [
      "new ideas",
      "curiosity",
      "thirst for knowledge",
      "new ways of communicating",
    ],
  },
  {
    name: "Knight of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    image: "/images/knightOfSwords.png",
    index: 61,
    keywords: [
      "ambitious",
      "action-oriented",
      "driven to succeed",
      "fast-thinking",
    ],
  },
  {
    name: "Queen of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    image: "/images/queenOfSwords.png",
    index: 62,
    keywords: [
      "independent",
      "unbiased judgement",
      "clear boundaries",
      "direct communication",
    ],
  },
  {
    name: "King of Swords",
    type: "Minor Arcana",
    suit: "Swords",
    image: "/images/kingOfSwords.png",
    index: 63,
    keywords: ["mental clarity", "intellectual power", "authority", "truth"],
  },
  // Minor Arcana - Pentacles
  {
    name: "Ace of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 1,
    image: "/images/aceOfPentacles.png",
    index: 64,
    keywords: ["manifestation", "new financial opportunity", "prosperity"],
  },
  {
    name: "Two of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 2,
    image: "/images/twoOfPentacles.png",
    index: 65,
    keywords: [
      "multiple priorities",
      "time management",
      "prioritisation",
      "adaptability",
    ],
  },
  {
    name: "Three of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 3,
    image: "/images/threeOfPentacles.png",
    index: 66,
    keywords: ["teamwork", "collaboration", "learning", "implementation"],
  },
  {
    name: "Four of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 4,
    image: "/images/fourOfPentacles.png",
    index: 67,
    keywords: [
      "saving money",
      "security",
      "conservatism",
      "scarcity",
      "control",
    ],
  },
  {
    name: "Five of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 5,
    image: "/images/fiveOfPentacles.png",
    index: 68,
    keywords: [
      "financial loss",
      "poverty",
      "lack mindset",
      "isolation",
      "worry",
    ],
  },
  {
    name: "Six of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 6,
    image: "/images/sixOfPentacles.png",
    index: 69,
    keywords: [
      "giving",
      "receiving",
      "sharing wealth",
      "generosity",
      "charity",
    ],
  },
  {
    name: "Seven of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 7,
    image: "/images/sevenOfPentacles.png",
    index: 70,
    keywords: [
      "long-term view",
      "sustainable results",
      "perseverance",
      "investment",
    ],
  },
  {
    name: "Eight of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 8,
    image: "/images/eightOfPentacles.png",
    index: 71,
    keywords: [
      "apprenticeship",
      "repetitive tasks",
      "mastery",
      "skill development",
    ],
  },
  {
    name: "Nine of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 9,
    image: "/images/nineOfPentacles.png",
    index: 72,
    keywords: [
      "abundance",
      "luxury",
      "self-sufficiency",
      "financial independence",
    ],
  },
  {
    name: "Ten of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    number: 10,
    image: "/images/tenOfPentacles.png",
    index: 73,
    keywords: [
      "wealth",
      "financial security",
      "family",
      "long-term success",
      "contribution",
    ],
  },
  {
    name: "Page of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    image: "/images/pageOfPentacles.png",
    index: 74,
    keywords: ["manifestation", "financial opportunity", "skill development"],
  },
  {
    name: "Knight of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    image: "/images/knightOfPentacles.png",
    index: 75,
    keywords: ["hard work", "productivity", "routine", "conservatism"],
  },
  {
    name: "Queen of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    image: "/images/queenOfPentacles.png",
    index: 76,
    keywords: [
      "nurturing",
      "practical",
      "providing financially",
      "working parent",
    ],
  },
  {
    name: "King of Pentacles",
    type: "Minor Arcana",
    suit: "Pentacles",
    image: "/images/kingOfPentacles.png",
    index: 77,
    keywords: [
      "wealth",
      "business",
      "leadership",
      "security",
      "discipline",
      "abundance",
    ],
  },
];

export const tarotCardMap = new Map(
  tarotCards.map((card, index) => [card.name, index])
);
